CC = gcc
CFLAGS = -Wall -Isrc
# Default target: build main program
all:
$(CC) $(CFLAGS) src/calculator.c src/main.c -o calculator
# Target to compile and run tests
test:
$(CC) $(CFLAGS) src/calculator.c tests/test
calculator.c -o test
_
_
./test
runner
runner
_
clean:
rm -f calculator test
runner